INSERT INTO CLIENTE(NOMBRE, APELLIDO, EMAIL)
VALUES ('Parker', 'Peter', 'peterparker@gmail.com');

INSERT INTO TARJETA_CREDITO(NOMBRE_TARJETA, NUMERO_TARJETA, TIPO_TARJETA, MES_EXP, AÑO_EXP, CCV)
VALUES ('Peter Parker', '4565 9018 2124 2422', 'VISA', '07', '2024', '212');

INSERT INTO DIRECCION(CALLE, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL)
VALUES ('3142 McDonald Street', 'Brooklyn', 'NY', 'USA', '11201');

INSERT INTO CUENTA(DIRECCION_ID, CLIENTE_ID, TARJETA_CREDITO_ID, ESTADO)
VALUES (1, 1, 1, 'ACTIVO');